export { default as login } from './auth/login.js'
export { default as register } from './auth/register.js'

export { default as getUser } from './users/getUser.js'
export { default as updateUser } from './users/updateUser.js'
export { default as deleteUser } from './users/deleteUser.js'
export { default as followUser } from './users/followUser.js'
export { default as unFollowUser } from './users/unFollowUser.js'

export { default as createPost } from './posts/createPost.js'
export { default as getPost } from './posts/getPost.js'
export { default as updatePost } from './posts/updatePost.js'
export { default as deletePost } from './posts/deletePost.js'
export { default as likePost } from './posts/likePost.js'
export { default as feed } from './posts/feed.js'
